name: cpbs7601
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.3
  - jupyter=1.0
  - ipykernel
  - r-irkernel
  - nb_conda_kernels
  - papermill

  # Python packages
  - pandas=2.0
  - numpy=1.25
  - matplotlib
  - seaborn
  - plotnine

  # R packages
  - r-tidyverse=2.0
  - r-ggplot2=3.4
  - r-patchwork
  - r-ggrepel
