name: jupyter_conda_environment_cpbs7601
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.3
  - jupyter=1.0
  - r-irkernel=1.3
  - ipykernel=6.23
  - nb_conda_kernels=2.3

  # Python packages
  - pandas=2.0
  - numpy=1.25
  - matplotlib
  - seaborn

  # R packages
  - r-tidyverse=2.0
  - r-ggplot2=3.4
