---
default_language_version:
  python: python3.11
exclude: (^|/)nbconverted(/|$)|^lectures/9.software_packaging/.*
repos:
  # Fix common issues (e.g., whitespace errors)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Fix markdown formatting issues
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs

  # Format python code with black
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
      - id: black-jupyter

 # Standaridize python imports with isort
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort

  # Checks for common misspellings
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: |
              (?x)^(
                  .*\.csv |
                  .*\.ipynb
              )$
